apiVersion: v1
kind: Service
metadata:
  name: push-notification-service
spec:
  ports:
    - name: socket
      port: 2120
      targetPort: 2120
      nodePort: 32120
    - name: web
      port: 8082
      targetPort: 2121
      nodePort: 32121
  type: NodePort
  selector:
    module: push_server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushserver
spec:
  replicas: 1
  selector:
    matchLabels:
      module: push_server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        module: push_server
    spec:
      containers:
      - image: local_push_server
        imagePullPolicy: IfNotPresent
        name: push-notification
        ports:
        - name: socket
          containerPort: 2120
        - name: web
          containerPort: 2121
